#screen
SCREEN_HEIGHT = 800
SCREEN_WIDTH = 1200
BACKGROUND_COLOR = "black"
UPPER_PART = SCREEN_HEIGHT / 2
LOWER_PART = -SCREEN_HEIGHT / 2 
LEFT_PART = -SCREEN_WIDTH / 2
RIGHT_PART = SCREEN_WIDTH / 2
#playground 
BORDER_COLOR = "white"
LINE_THICK = 8
DRAW_BORDER = 0
#player 
PLAYER_COLOR = "white"
DRAW_PLAYER = 0
PLAYER_POSITION = (560, 0)
#computer
COMPUTER_COLOR = "white"
DRAW_COMPUTER = 0
COMPUTER_POSITION = (-560, 0)
#ball
BALL_COLOR = "white"
DRAW_BALL = 0
BALL_POSITION = (0,0)
BALL_SPEED = 1  #  0.6 slowest
#score 
SCORE_POSITION = (-60, 330) 
SCORE_COLOR = "white"
DRAW_SCORE  = 0 
#difficulty
C0MPUTER_SPEED = 8